# build-version.ps1
# Auto-increments the build counter and generates BuildVersion.g.cs + updates manifest.json
# Called by MSBuild pre-build target

param(
    [string]$ProjectDir = $PSScriptRoot
)

$versionFile = Join-Path $ProjectDir "version.json"
$generatedFile = Join-Path $ProjectDir "BuildVersion.g.cs"
$manifestFile = Join-Path $ProjectDir "manifest.json"

# Read version.json (create defaults if missing)
if (Test-Path $versionFile) {
    $ver = Get-Content $versionFile -Raw | ConvertFrom-Json
} else {
    $ver = [PSCustomObject]@{ full = 0; major = 1; minor = 0; build = 0; revision = 0 }
}

# Increment build counter
$ver.build = [int]$ver.build + 1

# Count total lines of source code (all .cs files, excluding auto-generated)
$totalLines = 0
Get-ChildItem -Path $ProjectDir -Filter "*.cs" -Recurse |
    Where-Object { $_.FullName -notmatch '\\obj\\' -and $_.Name -ne 'BuildVersion.g.cs' } |
    ForEach-Object { $totalLines += (Get-Content $_.FullName | Measure-Object -Line).Lines }
$ver.revision = $totalLines

# Write updated version.json
$ver | ConvertTo-Json | Set-Content $versionFile -Encoding UTF8

# Format version string: FULL.MAJOR.MINOR.BUILD.REVISION
$version = "$($ver.full).$($ver.major).$($ver.minor).$($ver.build).$($ver.revision)"

# Generate BuildVersion.g.cs
$cs = @"
// <auto-generated>
// This file is generated by build-version.ps1 on every build.
// Do not edit manually.
// </auto-generated>
namespace Plunder
{
    internal static class BuildVersion
    {
        public const string Version = "$version";
        public const int Build = $($ver.build);
    }
}
"@
Set-Content $generatedFile $cs -Encoding UTF8

# Update manifest.json version field (regex replace to preserve formatting)
if (Test-Path $manifestFile) {
    $manifestContent = Get-Content $manifestFile -Raw
    $manifestContent = $manifestContent -replace '("version"\s*:\s*")[^"]*"', "`${1}$version`""
    Set-Content $manifestFile $manifestContent -NoNewline -Encoding UTF8
}

Write-Host "Plunder version: $version (build $($ver.build))"
